name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  grcov:

    runs-on: ubuntu-latest

    steps:
      - name: rust-grcov
        uses: actions-rs/grcov@v0.1.5
