name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run the unit tests and compute the coverage score
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          profile: minimal

      - name: Run tests
        run: cargo test --quiet --all-features --no-fail-fast --workspace --exclude ilo_cli
        env:
          CARGO_INCREMENTAL: "0"
          RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests -Cinstrument-coverage"
          RUSTDOCFLAGS: "-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests -Cinstrument-coverage"

      - name: Gather coverage data
        id: coverage
        uses: actions-rs/grcov@d7fbf3f45736014e4361af190e8a5269060ace07
        with:
          args: >
            --output-type html
            --output-path ./coverage/
            ./target/debug

      - name: Deploy coverage to Vercel
        uses: amondnet/vercel-action@v20
        id: vercel-action
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: "--prod"
          github-comment: false
          working-directory: coverage
